import { TMenuItems, TOrder } from '@/modules/order/interface';

export const orders: TOrder[] = [
   {
      id: '1',
      name: 'Marlon',
      number: '10',
      status: 'free',
      description: '',
   },
   {
      id: '2',
      name: 'Fulano',
      number: '90',
      status: 'busy',
      description: '',
   },
   {
      id: '3',
      name: 'Marlon',
      number: '10',
      status: 'free',
      description: '',
   },
   {
      id: '4',
      name: 'Fulano',
      number: '90',
      status: 'busy',
      description: '',
   },
   {
      id: '5',
      name: 'Marlon',
      number: '10',
      status: 'free',
      description: '',
   },
   {
      id: '6',
      name: 'Fulano',
      number: '90',
      status: 'busy',
      description: '',
   },
   {
      id: '7',
      name: 'Marlon',
      number: '10',
      status: 'free',
      description: '',
   },
   {
      id: '8',
      name: 'Fulano',
      number: '90',
      status: 'busy',
      description: '',
   },
   {
      id: '9',
      name: 'Marlon',
      number: '10',
      status: 'free',
      description: '',
   },
];

export const menuItems: TMenuItems[] = [
   { id: '1', item: 'Batata frita', price: 15 },
   { id: '2', item: 'Hamburguer', price: 25 },
   { id: '3', item: 'Hamburguer', price: 25 },
   { id: '4', item: 'Hamburguer', price: 25 },
   { id: '5', item: 'Hamburguer', price: 25 },
   { id: '6', item: 'Hamburguer', price: 25 },
   { id: '7', item: 'Hamburguer', price: 25 },
   { id: '8', item: 'Hamburguer', price: 25 },
   { id: '9', item: 'Hamburguer', price: 25 },
   { id: '10', item: 'Hamburguer', price: 25 },
   { id: '11', item: 'Hamburguer', price: 25 },
   { id: '12', item: 'Hamburguer', price: 25 },
   { id: '13', item: 'Hamburguer', price: 25 },
   { id: '14', item: 'Hamburguer', price: 25 },
   { id: '15', item: 'Hamburguer', price: 25 },
];
